### ISSUE TITLE
Can i remove Select / Radio / Checkbox Value field and set Default value as per Text

### ISSUE THREAD

**Issue by raviozainfo** [kevinchappell/formBuilder#1336]
### Description:
Hi, I want to remove Value from Select / Checkbox / Radio in option and need to set value as per Its Text.
Or its ok if what i am typing in text fields will auto set in Value.

### Environment Details:

 - formBuilder Version: 
 - Browser: 
 - OS: 

### Expected Behavior
![image](https://user-images.githubusercontent.com/34629055/195771710-1ecdf508-5148-420f-a1b9-ab5ec8e516c1.png)

**Comment by lucasnetau** [comment]
Not directly in formBuilder but you could try the following

The options are wrapped by <div class="form-group field-options">

Add styles to hide the value and expand the label

```css
.form-wrap.form-builder .frmb input.option-label.option-attr {
    width: calc(89% - 17px) !important;
}
.form-wrap.form-builder .frmb input.option-value.option-attr {
    display: none;
}
```

then hook into the input event to update the value field when the label field is changed

```javascript
$('#fb-editor').on('input','.form-wrap.form-builder .frmb input.option-label.option-attr', (event) => {
    $(event.target).siblings('.option-value').val($(event.target).val());
});
```

NOTE: I haven't tested this in practice, it should work but code will need to be double checked
