### ISSUE TITLE
i18n string is altered to title case

### ISSUE THREAD

**Issue by mtthwprtchrd** [kevinchappell/formBuilder#1394]
### Description:
There is an issue when the i18n string is altered to title case e.g. each word in a phrase is capitalised, in my case "Read-only" is altered to read "Read-Only".

### Environment Details:

 - formBuilder Version: 3.8.2
 - Browser: Chrome 115.0.5790.171 (Official Build) (64-bit)
 - OS: Windows 10

### Expected Behavior
Original case of i18n string is respected.

### Actual Behavior
The case of the i18n string is altered to title case e.g. "Read-only" becomes "Read-Only"

### Steps to Reproduce
See the customAttribute string in the code pen below.

The English string "Select {count} options" becomes "Select 3 **O**ptions".
The German string "Wählen Sie {count} Optionen aus" becomes "Wählen Sie 3 Optionen **A**us".

https://codepen.io/Matthew-Pritchard/pen/vYvEomQ

**Comment by lucasnetau** [comment]
This transformation is done via CSS (text-transform: capatalize). You can add this rule to your stylesheet to override.

```css
.form-wrap.form-builder .frmb .form-elements .false-label:first-child, .form-wrap.form-builder .frmb .form-elements label:first-child {
    text-transform: none;
}
```

One thing you'll notice is the shape options are showing the german translation for the colours. You need to define red/green/blue translations in the en-US lang list too.

```javascript
              "en-US": {
                  red: "Red",
                  green: "Green",
                  blue: "Blue",
              },
```
