### ISSUE TITLE
Save Button Background Color

### ISSUE THREAD

**Issue by llvasconcellos** [kevinchappell/formBuilder#315]
I don't think you should set background color for buttons if you already use classes such as btn-primary. The reason is that my btn-primary is green and not blue so for now I'm using !important to bypass this problem.

form-builder.css: 878

``` css
[id^='frmb-'][id$='-form-wrap'] .btn-primary:hover, [id^='frmb-'][id$='-form-wrap'] .btn-primary:active, [id^='frmb-'][id$='-form-wrap'] .btn-primary.active, [id^='frmb-'][id$='-form-wrap'] .btn-primary.btn-active {
    background-color: #286090;
    border-color: #204d74;
}
```

**Comment by llvasconcellos** [comment]
My white "cancel" button is also being affected by the form-builder.css because it's setting the font color to also white.

form-builder: 835
```css
[id^='frmb-'][id$='-form-wrap'] .btn {
    color: #fff;
    display: inline-block;
    padding: 6px 12px;
    margin-bottom: 0;
    font-size: 14px;
    font-weight: 400;
    line-height: 1.42857143;
    text-align: center;
    white-space: nowrap;
    vertical-align: middle;
    -ms-touch-action: manipulation;
    touch-action: manipulation;
    cursor: pointer;
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
    background-image: none;
    border: 1px solid transparent;
    border-radius: 4px;
}
```
