### ISSUE TITLE
How to remove of disabled Label, class and Help Text

### ISSUE THREAD

**Issue by piyusharc** [kevinchappell/formBuilder#366]
Hello

I'm using form builder  for a college project, everything is working superb. I just want to know how to disabled or hide "Help text, Label and class" field while edit the radio ot checkbox button after Drag them to canvas.

please help

**Comment by kevinchappell** [comment]
formBuilder does not provide an api for doing this but it can be done with css.

```scss
.checkbox-field,
.button-field,
.radio-group-field {
  .description-wrap,
  .label-wrap,
  .className-wrap {
    display: none;
  }
}
```
css: https://jsfiddle.net/kevinchappell/7kqa591q/
scss: https://jsfiddle.net/kevinchappell/7kqa591q/2
